name: General Issue
description: Template for reporting an idea or not well defined issue.
title: "[Brief Description]"
labels: ["WIP"]
body:
  - type: textarea
    id: objective
    attributes:
      label: Objective
      description: "Provide a summary of the objective."
      placeholder: "Describe the goal or purpose of the issue."
    validations:
      required: true

  - type: textarea
    id: todo
    attributes:
      label: Todo
      description: "What needs to be done to achieve the objective."
      value: |
        - [ ] Investigate
        - [ ] Create 
        - [ ] Build
        - [ ] Measure
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: Notes / Assumptions
      description: "Provide any additional known context for this effort."
      value: |
        - TBD
        - TBD
        - TBD
    validations:
      required: false
